- .drone.yml
this does the following:
- signs the drone.yml
- allows using drone.yml for CI
> Chore: use drone.yml for CI

- pkg/plugin/twinmaker/client.go
this makes sure to use the `NextToken` in the `list*` type client queries to make sure we get all the results if there are more then the default limit of `200`
> Client: use NextToken for list client queries

- .vscode/launch.json
- pkg/plugin/datasource.go
- pkg/plugin/datasource_test.go
> HealthCheck: show the original error on failed health check

- pkg/plugin/twinmaker/client.go
Testers were not able to use the gamma TwinMaker service endpoint and specify an AssumeRoleArn. This was due to the GetSession() method in grafana-aws-sdk using the custom endpoint to call STS.AssumeRole for the TwinMaker client. To get around this we remove the Endpoint from the session settings, get the session credentials, then add the endpoint field back when instantiating the client.
> Bug fix: allow using an AssumeRole ARN and a custom service endpoint

- pkg/plugin/twinmaker/utils.go
- src/datasource/components/ConfigEditor.tsx
1. Customers that use our samples to build their Lambdas will have an externalIdProperty in the History response of their alarms like the following:
```
externalIdProperty: {
alarm_key: EXTERNAL_ID,
propertyName: alarm_status
}
```
Will recommend customers to update their Lambdas and remove the `propertyName`, but in the meantime we will ignore properties that aren't in the property list or aren't externalIds.
2. Updated the URL in the alert pointing to our documentation on setting up the TwinMaker Dashboard Role
> More resilient check for valid externalId in externalIdProperty response

- pkg/plugin/resource.go
- pkg/plugin/twinmaker/client.go
- pkg/plugin/twinmaker/client_test.go
The frontend plugins that make AWS SDK calls on the browser get credentials from a 'token' backend resource call. This calls the functions GetSessionToken and HandleGetToken. Added logic to display an error whenever an Assume Role ARN is missing from the datasource configuration to ensure that the SceneViewer and VideoPlayer cannot be used to make calls with the authentication provider credentials directly.
> Enforce Assume Role ARN in GetToken calls

- src/common/variables.ts
- src/datasource/dashboards/twinmaker-alarm-dashboard.json
- src/datasource/dashboards/twinmaker-main-dashboard.json
Dependent on https://github.com/grafana/grafana/pull/51003. Fixes https://github.com/grafana/grafana-iot-twinmaker-app/issues/67
Before:
After:
> Prevent panel refresh on data link clicks

- src/common/variables.ts
- src/datasource/dashboards/twinmaker-alarm-dashboard.json
- src/datasource/dashboards/twinmaker-main-dashboard.json
Bugs:
* Scene Viewer - clicking on a tag does not move the camera to face it
* Query editor - cannot use any template variables in the query editor. The "value" does not have `$` so the temp var name is treated as a TwinMaker ID/name
Need to investigate fixing these issues before moving forward with the panel refresh change.
> Reverting changes for preventing panel refresh on data link clicks

- src/common/dashboard.ts
- src/common/managerSimple.ts
- src/panels/layout/LayoutPanel.tsx
- src/panels/layout/merge.ts
- src/panels/scene-viewer/helpers.ts
Refreshing the page in explore causes this error in the query editor:
The query editor was attempting to access the current dashboard, which doesn't exist in explore. This change prevents an empty result from throwing an exception.
> Data source: Prevent editor error in explore

- pkg/plugin/twinmaker/handler.go
- pkg/plugin/twinmaker/utils.go
We PR 84 for how to test alarm configuration (https://github.com/grafana/grafana-iot-twinmaker-app/pull/84).  
Current TwinMaker API only allows for direct child to be search for by list-component-types API when using the extendsFrom.  Thus to enable finding extensions of both the basic alarm and the new sitewise 1p alarm we need to do two queries even though the sitewise 1P alarm component type is extended from the twinmaker basic alarm component type.
This was testing using entities that have 2 alarms of the same componentType on the same entity which exposed an issue with an extra 'break' in the utils.go that caused the search to exit on the first matching componentType even if the externalId didn't match.
> extend alarm list to support basic and sitewise alarm extensions

- src/datasource/README.md
Given that the "Assumer role ARN" is now required, we need to update the README to reflect this.
> Updated dashboard datasource readme

- pkg/plugin/twinmaker/client_mock.go
- src/datasource/components/BlurTextInput.tsx
- src/datasource/components/QueryEditor.tsx
Also only allows typing numbers.  Fixes #91
> Streaming: hide streaming options when streaming is not available

- pkg/models/query.go
- pkg/plugin/datasource.go
- src/common/manager.ts
- src/datasource/components/QueryEditor.tsx
- src/datasource/datasource.ts
- src/datasource/requestLooper.ts
Fixes #95 by providing a fallback for paged responses by using the frontend request looper from `v1.x` in instances where Grafana Live is not enabled or available.
> DataSource: Add frontend request looper fallback

- pkg/plugin/resource.go
- src/datasource/datasource.ts
- src/panels/alarm-configuration/AlarmConfigurationPanel.tsx
- src/panels/alarm-configuration/AlarmEditModal.tsx
`postResource` specifies `any` for the request body, but expects [the body to be an object](https://github.com/grafana/grafana/blob/cc6fae18db70cd345c11e0545f0b7239cc56b1f4/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L240).
Wraps `entries` in an object so that it's compatible with `postResource`.
> Fix postResource req body

- pkg/plugin/twinmaker/client.go
Make the plugin datasource save & test button (along with any other use of GetSessionToken) make sure the write ARN is a valid arn. Doesn't verify that it has write permissions, just that it can assume the provided ARN.
> Datasource test button makes sure we can assume a provide write ARN

- pkg/plugin/twinmaker/client.go
- pkg/plugin/twinmaker/client_test.go
- pkg/plugin/twinmaker/testdata/get-property-value-athena.golden.jsonc
- src/datasource/components/ConfigEditor.tsx
* Clear writer role field when `Define write permissions for Alarm Configuration Panel` checkbox is unchecked
* BatchPutPropertyValues returns an error when the writer role is empty
> Writer role fixes

- pkg/plugin/twinmaker/client.go
Reverse existence check made save & test for Write ARNs always fail.
> fix equality test for tokenRoleWrite exists

- src/common/constants.ts
- src/common/managerSimple.ts
- src/panels/alarm-configuration/AlarmConfigurationPanel.tsx
Fixes issue where updating the Alarm Threshold in View will not have the edit carry over to Edit mode.
Also addresses issue where the dashboard is viewing data in the past and submitting an Alarm Threshold change will update the panel data even though the panel should be using the dashboard time range and thus not change.
Reported by @haweston:
> Alarm Configuration: Refresh dashboard after alarm updates

- src/datasource/components/FilterQueryEditor.tsx
- src/datasource/components/QueryEditor.tsx
We check the dataType of the property filter via it's label, but recently the dataType has moved to the description.
https://github.com/grafana/grafana-iot-twinmaker-app/blob/main/pkg/plugin/twinmaker/resource.go#L287
Also fixed a minor bug with the add filter button.
> fix(query-filter): Check property description for data type

- package.json
Adds the expected frontend test coverage script for the code coverage workflow.
Contributes to https://github.com/grafana/grafana-iot-twinmaker-app/issues/153
> Add test coverage scripts to package.json for code coverage workflow

- .github/workflows/issue_commands.yml
**What this PR does / why we need it**: 
Based on https://github.com/grafana/iot-sitewise-datasource/pull/165
Adds the type "unlabeled" so it triggers the removeFromProject action
> Add unlabeled type to trigger removeFromProject

- src/datasource/dashboards/twinmaker-alarm-dashboard.json
Adds a short explanation for using the sample Alarm Dashboard to the top of it
Fixes #152
> Twinmaker: Add info box to sample alarm dashboard

- cspell.config.json
- package.json
- yarn.lock
Our internal security team noted that we have potential vulnerabilities in our devDependencies. These stem from nested dependencies in @grafana and @iot-app-kit package dependencies.
For most of the vulnerabilities, they were patched in very similar versions to what's already in the dependency chain, so this shouldn't cause much of an issue. 
For these 2 dependencies, there was a significant shift in Major version, but from testing doesn't seem to impact the build of the customer application, so may appear when we run our automated tests, submitting this PR to find out.
```
"d3-color": "^3.1.0",
"log4js": "^6.4.0"
```
Fixes #
> fix npm audit vulnerabilities using resolutions

- src/panels/scene-viewer/SceneViewer.tsx
- src/panels/scene-viewer/module.ts
- src/panels/video-player/VideoPlayer.test.tsx
- src/panels/video-player/VideoPlayer.tsx
- tsconfig.json
- yarn.lock
When a dashboard has a multi-value template variable in a row that repeats for each value of the variable, each value was not set correctly in a repeated Video Player panel.
The Scene Viewer panel has different types of display options. 3 of these options are for setting the values of certain variables based on a selection in the scene. On load the value of the variables are used to initialize the selection, but it should only be resolved from the URL values. Grafana gives users the ability to save default values which cause issues for the Scene Viewer when deselecting items in the scene. 
1 option is for setting the default active camera which can be resolved by the URL or default dashboard value since it cannot be deselected.
Fixed by …
> Fix template repeat for custom panels

- .github/CODEOWNERS
Reduces our (the grafana team's) code ownership to just the github files, the go code, and the frontend datasource code. Hopefully this improves the Twinmaker team's development experience.
Notes:
According to [this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) I'm fairly sure the un-owned code will not have us as code owners and thus will not require our approval to be merged. I can add other files if we think that we should be controlling access to them.
> Edit codeowner permissions

- src/panels/video-player/VideoPlayer.tsx
- src/panels/video-player/styles.ts
- Improves video player user experience.
- Applies sticky placement to the `video-upload-request-ui` block.
https://user-images.githubusercontent.com/6610619/236571832-afe35cb2-c4df-4e48-a09d-bd18500a5b63.mov
> feat(TwinMaker): Setting up sticky video controls

- package.json
- src/common/info/info.ts
- src/datasource/components/ConfigEditor.test.tsx
- src/datasource/components/ConfigEditor.tsx
- src/datasource/datasource.ts
- yarn.lock
Implements logic for only fetching workspaces when 
- the datasource is saved
- the dropdown is clicked
As described in [this ticket](https://github.com/grafana/grafana-iot-twinmaker-app/issues/154), the workspace handling was confusing and there wasn't info that the DS should be saved before selecting workspaces. 
It looks like this now: 
With new datasource
With an already saved datasource:
The only thing I don't love right now is that there is an error for missing workspace when the user saves for the first time. Lmk if you want me to spend some time on improving that. 
Fixes https://github.com/grafana/grafana-iot-twinmaker-app/issues/154
I also refactored the component from …
> Query editor: Improve workspace loading

- src/datasource/components/ConfigEditor.tsx
When the user (me) opens the workspaces menu, there often isn't enough room on the bottom for the whole menu to be visible:
After: 
This change makes it open on the top. Don't love that the menu doesn't stand out, but I think this is an improvement nonetheless? 🤔
Fixes #
> Config Editor: Open Workspaces menu on the top

- CHANGELOG.md
- package.json
- src/panels/query-editor/QueryEditor.tsx
As suggested [here](https://github.com/grafana/grafana/issues/75422#issuecomment-1736278952), we can wrap the Query Editor panel in the CustomScrollbar component from @grafana/ui to restore the scrolling behaviour. This is how it looks now (tested in Grafana 10 and 9):
Fixes https://github.com/grafana/grafana-iot-twinmaker-app/issues/224
> Wrap QueryEditor panel plugin in CustomScrollbar to fix scrolling behavior

- CHANGELOG.md
- package.json
- yarn.lock
There is a problem in loading the Scene with Matterport space due to a bug in the latest Matterport SDKs. Reverted the Matterport SDK versions to the last working versions.
These are the same versions used in the iot-app-kit.
Fixes #232 
**Special notes for your reviewer**: No impact on other functionalities
> fix(Matterport-Scene): Use specific version of Matterport SDK

- src/datasource/dashboards/twinmaker-alarm-dashboard.json
This PR changes the dashboard JSON's filter value from a simple string to the expected struct.
The structure changed about a year ago: https://github.com/grafana/grafana-iot-twinmaker-app/pull/118/files#diff-c4f0fcff0253fa91c051c3b3a8897168273aa7c3a5cc78b9dbfbaa58f21a88d0L34
Fixes https://github.com/grafana/grafana-iot-twinmaker-app/issues/239
Here's how this change looks (no more error and ACTIVE is set):
> Fix imported Alarm Dashboard's filter value from string to struct

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
As part of our work to shift from discussions to github issues we'd like to ensure that all new feature requests open as github issues. 
See https://github.com/grafana/grafana/discussions/73424
> New Feature requests open as github issues rather than discussions

- CHANGELOG.md
- cspell.config.json
- package.json
- Bump go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace from 0.42.0 to 0.44.0 by @dependabot in https://github.com/grafana/grafana-iot-twinmaker-app/pull/237
- Fix imported Alarm Dashboard's filter value from string to struct by @fridgepoet in https://github.com/grafana/grafana-iot-twinmaker-app/pull/240
- Bump @babel/traverse from 7.22.15 to 7.23.2 by @dependabot in https://github.com/grafana/grafana-iot-twinmaker-app/pull/241
- Bump google.golang.org/grpc from 1.58.2 to 1.58.3 by @dependabot in https://github.com/grafana/grafana-iot-twinmaker-app/pull/242
> Prepare v1.9.2

- CHANGELOG.md
Updates the changelog to include https://github.com/grafana/grafana-iot-twinmaker-app/pull/252
> Update Changelog for v1.9.3

- CHANGELOG.md
- package.json
- src/datasource/components/ConfigEditor.tsx
In the old form styling, the Workspaces Select input was set to be disabled if there were no workspaces. This doesn't seem to do anything, since the default state is `[]` but the user is still able to click on it. This is ok, since the fetchWorkspaces function is only called on opening the dropdown. 
However, in the new form styling the `disabled` attribute is applied, so the user is unable to fetch workspaces for a new Twinmaker datasource. Probably should have caught this earlier, but better late than never I guess 😔
I removed the disabled attribute, since the flow works perfectly fine without it (i.e. the same as in the old form styling). 
Fixes #
> Config editor: Fix workspace loading in new form styling and prepare 1.10.0

- package.json
- yarn.lock
The changes included in this PR is to set the versions of a few NPM packages to a specific target. There is problem running React 18 based plug-in on the Grafana version < 10 (which are React 17 based). Due to this, scene does not loads in the scene viewer panel. This is a major problem for AMG as it runs Grafana version < 10.
This change was there when we first released the React 18 version of the plug-in but was overwritten unintentionally.
> fix(scene-viewer): loading scene in AMG

- src/datasource/components/QueryEditor.tsx
Noticed I missed the tooltip when migrating to new form styling, oops!
> Bugfix: Add tooltip on interval field

- CHANGELOG.md
- package.json
- src/datasource/regions.ts
IoT TwinMaker is launching to the cn-north-1 (BJS) region, so we need to add this region as an option in the datasource region dropdown.
Fixes #
> Support for cn-north-1 (BJS)

- pkg/plugin/twinmaker/utils.go
- pkg/plugin/twinmaker/utils_test.go
A community member followed a tutorial for setting up Twinmaker that had timestamp in unix time. They were getting [duplicated results](https://github.com/grafana/grafana-iot-twinmaker-app/issues/263) due to the plugin sending time string to GetPropertyValueHistory in string with only second precision. 
When we query streaming, we set the startTime to the latest timestamp of the previous set of results. The startTime we were sending was always set to second + 0 milliseconds (second precision): `timeObject.Format(time.RFC3339)`, so it would always actually query ***before*** the last timestamp. 
For example, our last entry was at `2024-01-08T19:58:34.123+01:00`.  The util function was parsing it into `2024-01-08T19:58:34+01:00`, losing the …
> Convert time objects to strings with nanosecond precision

- src/datasource/components/FilterQueryEditor.tsx
Fixes from the new form styling bug bash
- Disable delete button if there's only one filter and it's empty
- Fix capitalization in tooltip
Fixes #
> New Form Styling: improvements

- CHANGELOG.md
- package.json
- Query Editor: Disable delete if only one filter, fix tooltip (new form styling) in [#268](https://github.com/grafana/grafana-iot-twinmaker-app/pull/268)
- GetPropertyValueHistory: Convert time objects to strings with nanosecond precision [#264](https://github.com/grafana/grafana-iot-twinmaker-app/pull/264)
> Prepare 1.11.1

- CHANGELOG.md
- go.mod
- go.sum
- package.json
- src/datasource/components/QueryEditor.test.tsx
Part of https://github.com/grafana/grafana-aws-sdk/issues/113
Also changed a confusing test name
> Update grafana/aws-sdk-go to 0.20.0 and prepare 1.12.0

- CHANGELOG.md
- package.json
New build for [security fixes in go 1.21.8](https://groups.google.com/g/golang-announce/c/5pwGVUPoMbg).
> Prepare v1.14.0

- src/plugin.json
This ensures that we are able to serve the twinmaker app from the plugin CDN.
Note: Given the naming of the `plugin.json` file of the nested alarm panel (`plugin_SKIP.json`) - this has been omitted as it will not be loaded by Grafana anyway.
> Add nested plugin to app includes

- package.json
- src/datasource/components/ConfigEditor.test.tsx
- src/datasource/components/ConfigEditor.tsx
- src/datasource/components/FilterQueryEditor.tsx
- src/datasource/components/OrderByEditor.tsx
- src/datasource/components/QueryEditor.test.tsx
- src/datasource/components/QueryEditor.tsx
- src/datasource/dashboards/twinmaker-main-dashboard.json
- src/panels/query-editor/QueryEditor.tsx
- yarn.lock
Removes the newFormStyling feature toggle, making the new styling default. Part of grafana/oss-plugin-partnerships#692
> Migrate to new form styling in config and query editors

- CHANGELOG.md
- package.json
- src/datasource/components/ConfigEditor.tsx
I realized we weren't using Grafana theme for the Config editor width, so squeezing that in here too ('width-30' will be deprecated at some point)
- Use Grafana theme for config editor width in [#290](https://github.com/grafana/grafana-iot-twinmaker-app/pull/290)
- Migrate to new form styling in config and query editors in [#289](https://github.com/grafana/grafana-iot-twinmaker-app/pull/289)
- add nested plugin to app includes in [#288](https://github.com/grafana/grafana-iot-twinmaker-app/pull/288)
- Remove relative path info from executable field in [#282](https://github.com/grafana/grafana-iot-twinmaker-app/pull/282)
> Prepare release 1.16.0

- src/panels/alarm/TwinMakerAlarmPanel.tsx
In Grafana 12, we'll be [removing Angular support](https://grafana.com/blog/2024/03/11/removal-of-angularjs-support-in-grafana-what-you-need-to-know/). As part of that, we'll also be removing a lot of legacy CSS classes.
Twinmaker has a panel-empty class that relies on one of the deprecated classes.
Fixes #287 
Also switched to css object styles for this file, as Grafana style guide suggests.
> Alarm panel: Replace deprecated styles 

- .github/dependabot.yml
Adds a dependabot config to update dependencies on a weekly cadence. It'll group dependency updates according to the package ecosystem to reduce PR noise.
Fixes https://github.com/grafana/oss-plugin-partnerships/issues/931
I've left the packages in the `@iot-app-kit`, `@aws-sdk`, and `@cloudscape-design` scopes to be ignored by dependabot so they will need to be manually updated. I believe these packages are updated by the twinmaker team as needed.
> Chore: add dependabot

- CHANGELOG.md
- cspell.config.json
- package.json
+ Had to revert an update to the build scripts I did in https://github.com/grafana/grafana-iot-twinmaker-app/pull/328
- Dependency updates:
- Node in [#325](https://github.com/grafana/grafana-iot-twinmaker-app/pull/325), [#326](https://github.com/grafana/grafana-iot-twinmaker-app/pull/326), [#315](https://github.com/grafana/grafana-iot-twinmaker-app/pull/315), [#316](https://github.com/grafana/grafana-iot-twinmaker-app/pull/316), [#312](https://github.com/grafana/grafana-iot-twinmaker-app/pull/312):
- actions/checkout@v3 to actions/checkout@v4
- actions actions/setup-node@v3 to actions/setup-node@v4
- Bump ws from 8.13.0 to 8.18.0
- Bump micromatch from 4.0.5 to 4.0.8
- Bump webpack from 5.93.0 to 5.94.0
- @emotion/css from 11.11.2 to 11.13.5
- @grafana/aws-sdk from 0.4.1 to 0.5.0
- …
> Prepare 1.18.3

- .github/dependabot.yml
I ran into issues when an update to react 19.0 was submitted in a dependabot PR. Grafana main runs on react@18, so there was a mismatch and subsequent errors. Not sure if there's a better way to do it than this, but we probably dont want to include major updates to react and react-dom in every dependabot PR. 
Fixes #
> Dependabot config: Ignore react and react-dom major updates

- src/common/manager.ts
- src/common/managerSimple.ts
- src/datasource/components/QueryEditor.tsx
- src/datasource/queryInfo.ts
- src/hooks/usePanelRegistration.ts
- src/panels/scene-viewer/ScenePanel.tsx
This removes code related to something called Twinmaker Panel query. while migrating to scenes, I noticed that it was commented out in the query type options, so I removed it, and related functions, to make it easier to migrate. I also removed the `refresh` method from the dashboard manager, since that wasn't used anywhere either. 
Fixes #
> Remove TwinmakerPanel query code

- CHANGELOG.md
- package.json
- Chore: add label to external contributions in [#358](https://github.com/grafana/grafana-iot-twinmaker-app/pull/358)
- Migrate dashboard utils to Scenes in [#383](https://github.com/grafana/grafana-iot-twinmaker-app/pull/383)
- Remove TwinmakerPanel query code in [#382](https://github.com/grafana/grafana-iot-twinmaker-app/pull/382)
- Update pr-commands.yml in [#391](https://github.com/grafana/grafana-iot-twinmaker-app/pull/391)
- Use vault to generate token in [#390](https://github.com/grafana/grafana-iot-twinmaker-app/pull/390)
- Update github actions files in [#388](https://github.com/grafana/grafana-iot-twinmaker-app/pull/388)
- Bump node dependencies in [#365](https://github.com/grafana/grafana-iot-twinmaker-app/pull/365), [#371](https://github.com/grafana/grafana-iot-twinmaker-app/pu …
> Prepare 2.0.1

- pkg/models/settings.go
- pkg/plugin/datasource.go
- pkg/plugin/twinmaker/client.go
- src/datasource/components/ConfigEditor.tsx
Fixes: https://github.com/grafana/oss-plugin-partnerships/issues/1220
[Instructions for testing PDC locally](https://wiki.grafana-ops.net/w/index.php/Engineering/Grafana/Data_Sources/API_servers/Testing_datasources_with_PDC_Locally).
New secure socks proxy setting added below the region selector in the config page
> Add PDC support
