grafana/grafana-iot-twinmaker-app

src/README.md, src/panels/scene-viewer/README.md, src/panels/video-player/README.md
this fixes the img paths for the app plugin and panel READMEs
=> Chore: fix README img paths

.gitignore, cypress/integration/something.ts, cypress/tsconfig.json, package.json, yarn.lock
this includes the scaffolding for the e2e testing along with a dummy test to make sure we are integrated with the ci process
=> Chore: include e2e testing scaffold

pkg/plugin/twinmaker/utils.go
Updated the in-line session policy for the video panel to have the scoped down permissions which are required.
=> Update the in-line session policy for the video panel

.drone.yml
this includes a manually generated drone config for the ci/cd pipeline
=> Chore: switch to using manual drone config

go.mod, go.sum, pkg/plugin/twinmaker/handler.go
Upgrade Go SDK to v1.43.38
Added nil checks to client responses of backend query handlers.
=> Upgrade GoLang SDK to v1.43.38

go.mod, go.sum, pkg/plugin/twinmaker/handler.go, pkg/plugin/twinmaker/testdata/get-property-history-alarms-w-id.json, pkg/plugin/twinmaker/testdata/get-property-history-alarms.json
Update AWS Go SDK to latest version 1.44.1
=> Update AWS Go SDK to latest version 1.44.1

pkg/plugin/datasource.go, pkg/plugin/datasource_test.go, src/datasource/components/ConfigEditor.tsx
For security reason, we are making this field required. Users will not be able to save and test datasource if this field is missing. 
I also edited the alert we have.
=> ConfigEditor: make Assume Role Arn field required

package-lock.json, src/common/info/info.ts, src/datasource/components/QueryEditor.tsx, src/datasource/datasource.ts, src/panels/scene-viewer/SceneViewer.tsx, src/panels/scene-viewer/helpers.test.ts, src/panels/scene-viewer/helpers.ts, src/panels/scene-viewer/module.ts, src/panels/scene-viewer/types.ts
* Adds the Selected Property for an entity as well to be updated or set as the initial values.
* Enable using template variables in the selected property field of relevant queries (GetPropertyValueHistory and GetPropertyValue)
– Testing –
* Create a template variable for the selected property
* Attach it to the Scene Viewer display options
* Use the template variable in the "Selected Properties" field of the GetPropertyValueHistory queries
* Click different tags and see successful queries in other panels using the template variables
* Use a template variable in all queries with GetPropertyValueHistory and GetPropertyValue
=> Expose selected tag propertyName in SceneViewer

pkg/plugin/twinmaker/client.go, src/datasource/components/FilterQueryEditor.tsx, src/datasource/components/QueryEditor.tsx
GetPropertyValueHistory does not return data as expected when a maxResults of 0 is used in the API call.
Updated the backend and frontend to avoid the possibility of using 0.
=> Cannot set a maxResults of 0 for GetPropertyValueHistory

CHANGELOG.md, package.json
Update version to v1.2.0 for release
=> Update version to v1.2.0

src/datasource/plugin.json
=> Enable Alerting in plugin.json

yarn.lock
=> Fixed yarn.lock file

src/datasource/components/QueryEditor.tsx
Fix for #89 by setting min to 1 for max results field
=> Set min to 1 for max results for GetAlarm query

CHANGELOG.md, package.json
Update version to v1.2.1 for release
=> Update version to v1.2.1 for release

go.sum, pkg/models/query.go, pkg/plugin/twinmaker/client.go
=> Fixes issue with multiple Athena tabular conditions

CHANGELOG.md, package.json
- Bug fixes in Scene Viewer and Alarm Configuration panel
- Support property display name in queries
=> Update version to 1.3.1 for release

CHANGELOG.md
Added version number (v1.3.1) to change-log file
=> Added version number to changelog file

CHANGELOG.md, package.json
Update version to v1.6.2 for release
=> Prepare release v1.6.2

CHANGELOG.md, package.json, yarn.lock
Relates to https://github.com/grafana/oss-plugin-partnerships/issues/223
=> Upgrade sdk

src/transformer/registerTwinMakerLinks.ts
Fixes https://github.com/grafana/grafana-iot-twinmaker-app/issues/227 according to the docs here https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Table/Table.mdx#L25
Fixes https://github.com/grafana/grafana-iot-twinmaker-app/issues/227
=> Register Twinmaker Links transform: Modify custom cell type to display image

CHANGELOG.md, package.json
=> chore(release-1.9.1): Prepare for release v1.9.1

CHANGELOG.md, cspell.config.json, package.json
=> chore(release-1.9.3): Prepare for release v1.9.3

package.json
Added comment to avoid future confusions/overwrites - Do not remove react-three & Matterport dependencies until AMG upgrades to Grafana v10 - [PR#259](https://github.com/grafana/grafana-iot-twinmaker-app/pull/259)
=> chore(dependencies): Info about some package resolutions

CHANGELOG.md, package.json
=> chore(release-1.10.1): Prepare for release v1.10.1

package.json
**What this PR does / why we need it**: Upgrade plugin to v1.13.0
Fixes #
=> chore(release): upgrade plugin version to 1.13.0

CHANGELOG.md, package.json
Release latest bug fix
Fixes #
=> chore(release-1.17.0): fix scene viewer bug

CHANGELOG.md, package.json
Release for https://github.com/grafana/grafana-iot-twinmaker-app/pull/293
=> Release 1.17.1

CHANGELOG.md, package.json, src/plugin.json
=> Fix incorrect path for alarm configuration panel

package.json, yarn.lock
Bumping dompurify for https://github.com/advisories/GHSA-mmhx-hmjr-r674
=> Bump dompurify to 3.2.3

CHANGELOG.md, README.md, cspell.config.json, package.json
=> Prepare 2.0.0

package.json, pkg/plugin/twinmaker/client.go, src/common/dashboard.ts, src/common/manager.ts, src/common/managerSimple.ts, src/common/utils.ts, src/datasource/components/QueryEditor.tsx, src/datasource/queryInfo.ts, src/hooks/usePanelRegistration.ts, src/panels/alarm-configuration/AlarmConfigurationPanel.tsx, src/panels/scene-viewer/ScenePanel.tsx, yarn.lock
Blocked by https://github.com/grafana/grafana-iot-twinmaker-app/pull/382, which removes some unused code that also depends on Angular injector
This replaces angular injector, since it's been removed in Grafana 12. 
Tested in grafana 10.4.16, 11.4.x and 12-dev.
Fixes https://github.com/grafana/oss-plugin-partnerships/issues/1299
=> Migrate dashboard utils to Scenes

.github/workflows/detect-breaking-changes.yml, .github/workflows/e2e-tests.yml, .github/workflows/issue_commands.yml, .github/workflows/pr-commands.yml
Updates the github actions based on zizmor warnings
=> Update github actions files

.github/workflows/e2e-tests.yml, .github/workflows/pr-commands.yml, CHANGELOG.md, package.json
=> Prepare 2.0.2 release
